context("test-sort")
expectedSort <- c("havsil", "kutlingfamilien", "øyepål", "rødspette", "Tunge")
locales <- stringi::stri_locale_list()
s <- lapply(locales, function(loc) stringr::str_sort(expectedSort, locale = loc))
ss <- sapply(s, paste, collapse = ",")
#write(paste(names(table(ss)), table(ss), sep = ": ", collapse = "; "), "~/testtest.txt")
warning(paste(names(table(ss)), table(ss), sep = ": ", collapse = "; "))
cloc <- stringr::str_sort(expectedSort, locale = "C")
warning(paste(cloc, collapse = "; "))
expect_equal(expectedSort, cloc)
