on:
  push:
    branches:
      - main
      - master

name: pkgdown

jobs:
  pkgdown:
    # Use macOS here to speed up by binary R package install (and Windows may have more issues, such as Rtools)
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install R package dependencies
        run: |
          # Install the dependencies:
          # dependencies = TRUE installs "Depends", "Imports", "LinkingTo" and "Suggests", and the  "Depends", "Imports" and "LinkingTo" recursively from those dependencies
          remotes::install_deps(dependencies = TRUE, type = "both")
          
          # Used in "Deploy package" below:
          install.packages("pkgdown", type = "binary")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
